apiVersion: v1
kind: Pod
metadata:
  name: greeter-client-round-robin
spec:
  containers:
  - name: greeter-client-round-robin
    image: gcr.io/grpc-loadbalancing-demo2018/greeter_client:latest
    env:
    # Resolve backend IP using cluster-internal DNS name of the backend service
    - name: GREETER_SERVICE_TARGET
      value: "greeter-server.default.svc.cluster.local:8000"
    - name: GREETER_LB_POLICY_NAME
      value: "round_robin"
    #- name: GRPC_VERBOSITY
    #  value: "debug"
  restartPolicy: Never
